services:
  # 1. PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: immobili-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: immobili_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - immobili-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d immobili_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: immobili-elastic
    environment:
      - node.name=elastic-node-1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    networks:
      - immobili-network

  # 4. Eureka Server
  micro-eureka:
    build: ./backend/micro-eureka
    container_name: micro-eureka
    ports:
      - "8761:8761"
    networks:
      - immobili-network

  # 5. API Gateway
  micro-gateway:
    build: ./backend/micro-gateway
    container_name: micro-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://micro-eureka:8761/eureka/
      - "SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATIONS_[/**]_ALLOWEDORIGINS=*"
      - "SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATIONS_[/**]_ALLOWEDMETHODS=*"
      - "SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATIONS_[/**]_ALLOWEDHEADERS=*"
      - "SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATIONS_[/**]_ALLOWCREDENTIALS=true"

    depends_on:
      - micro-eureka
    networks:
      - immobili-network

  # 6. Property Service
  micro-properties:
    build: ./backend/micro-properties
    container_name: micro-properties
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/immobili_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://micro-eureka:8761/eureka/
    depends_on:
      - postgres-db
      - elasticsearch
      - micro-eureka
    networks:
      - immobili-network

  # 9. React Frontend
  frontend-react:
    build: ./frontend
    container_name: immobili-frontend
    ports:
      - "3000:80"
    depends_on:
      - micro-gateway
    networks:
      - immobili-network

networks:
  immobili-network:
    driver: bridge